name: CI/CD Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and deploy with Docker
        run: |
          cd /opt/apps/docs
          cp -r $GITHUB_WORKSPACE/* .
          docker compose down
          docker compose up -d --build
